kube_context_grafana: "bnekub03"
kube_storageclass_grafana: "bnenas05-nfs-csi"

grafana_ingress_host: "grafana.dev.randomnoun"
grafana_ingress_class: "nginx-internal"

grafana_tls_secret_cert: "{{ lookup('hashi_vault', 'mount_point=secret secret=secret/data/k8s/bnekub03/secret/grafana/grafana-tls-secret:tls.crt')}}"
grafana_tls_secret_key: "{{ lookup('hashi_vault', 'mount_point=secret secret=secret/data/k8s/bnekub03/secret/grafana/grafana-tls-secret:tls.key')}}"

grafana_volume_size_gb: 20


