kube_context_xwiki: ""
kube_namespace_xwiki: "dev-xwiki"
kube_storageclass_xwiki: "freenas-nfs"

xwiki_ingress_host: ""
xwiki_tls_secret_cert: ""
xwiki_tls_secret_key: ""

xwiki_volume_size_gb: 40

xwiki_db_host: ""
xwiki_db_schema: ""
xwiki_db_username: ""
xwiki_db_password: ""
