kube_context_gitlab: "bnekub03"
kube_storageclass_gitlab: "bnenas05-nfs-csi"

gitlab_ingress_host: "gitlab.dev.randomnoun"
gitlab_ingress_class: "nginx-internal"

gitlab_tls_secret_cert: "{{ lookup('hashi_vault', 'mount_point=secret secret=secret/data/k8s/bnekub03/secret/dev-gitlab/gitlab-tls-secret:tls.crt')}}"
gitlab_tls_secret_key: "{{ lookup('hashi_vault', 'mount_point=secret secret=secret/data/k8s/bnekub03/secret/dev-gitlab/gitlab-tls-secret:tls.key')}}"

gitlab_volume_size_gb: 256

gitlab_smtp_host: ""
gitlab_smtp_username: ""
gitlab_smtp_password: ""
