kube_context_nexus2: ""
kube_namespace_nexus2: "dev-nexus2"
kube_storageclass_nexus2: "freenas-nfs"

nexus2_ingress_host: ""
nexus2_tls_secret_cert: ""
nexus2_tls_secret_key: ""


nexus2_volume_size_gb: 256


