kube_context_commafeed: "bnekub02"
kube_storageclass_commafeed: "bnenas04-nfs-csi"

commafeed_ingress_host: "commafeed.dev.randomnoun"
commafeed_ingress_class: "nginx-internal"

commafeed_tls_secret_cert: "{{ lookup('hashi_vault', 'mount_point=secret secret=secret/data/k8s/bnekub02/secret/dev-commafeed/commafeed-tls-secret:tls.crt')}}"
commafeed_tls_secret_key: "{{ lookup('hashi_vault', 'mount_point=secret secret=secret/data/k8s/bnekub02/secret/dev-commafeed/commafeed-tls-secret:tls.key')}}"

commafeed_volume_size_gb: 40

commafeed_db_host: "bnesql02.dev.randomnoun"
commafeed_db_schema: "commafeed"
commafeed_db_username: "commafeed"
commafeed_db_password: "{{ lookup('hashi_vault', 'mount_point=secret secret=secret/data/db/bnesql02/commafeed:password')}}"
