---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: commafeed-pvc
spec:
  storageClassName: "{{ kube_storageclass_commafeed }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ commafeed_volume_size_gb }}Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed
  template:
    metadata:
      labels:
        app: commafeed
    spec:
      # this is needed to resolve bnesql02 from within the container. Note that 'Default' isn't the default, 'ClusterFirst' is
      # because of course it is.
      dnsPolicy: Default
      containers:
        - name: commafeed
          image: athou/commafeed:4.6.0
          resources:
            requests:
              memory: "2Gi"          
              ephemeral-storage: "4Gi"
            limits:
              memory: "2Gi"
          env:
            - name: CF_APP_PUBLICURL
              value: https://commafeed.dev.randomnoun/
            - name: CF_DATABASE_DRIVERCLASS
              value: com.mysql.cj.jdbc.Driver
            - name: CF_DATABASE_URL
              value: jdbc:mysql://{{ commafeed_db_host }}/{{ commafeed_db_schema }}?autoReconnect=true&failOverReadOnly=false&maxReconnects=20&rewriteBatchedStatements=true&timezone=UTC
            - name: CF_DATABASE_USER
              value: "{{ commafeed_db_username }}"
            - name: CF_DATABASE_PASSWORD
              value: "{{ commafeed_db_password }}"
          ports:
            - name: http
              containerPort: 8082
          volumeMounts:
            - name: commafeed-volume
              subPath: commafeed-data
              mountPath: "/commafeed/data"
#          livenessProbe:
#            failureThreshold: 3
#            initialDelaySeconds: 300
#            periodSeconds: 5
#            successThreshold: 1
#            timeoutSeconds: 10
#            httpGet:
#              path: /help
#              port: 80
#              scheme: HTTP
      volumes:
        - name: commafeed-volume
          persistentVolumeClaim:
            claimName: "commafeed-pvc"


---
apiVersion: v1
kind: Service
metadata:
  name: commafeed-service
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  selector:
    app: commafeed

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata: 
  name: commafeed-tls-secret
data: 
  tls.crt: "{{ commafeed_tls_secret_cert }}"
  tls.key: "{{ commafeed_tls_secret_key }}"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: commafeed-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/redirect-to-https: "false"
    nginx.org/client-max-body-size: "0"
    nginx.org/proxy-read-timeout: "600s"
    nginx.org/proxy-send-timeout: "600s"
    
spec:
  tls:
    - hosts:
        - {{ commafeed_ingress_host }}
      secretName: commafeed-tls-secret
  rules:
    - host: {{ commafeed_ingress_host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: commafeed-service
                port:
                  name: http
